### ISSUE TITLE
Move sup files from supervisor to detectors

### ISSUE THREAD

**Issue by cejkato2** [CESNET/Nemea-Detectors#7]
According to the mailing list (the following messages), `sup` files will be moved from the Nemea-Supervisor repo into this repo.

https://random.cesnet.cz/pipermail/nemea/2016-November/000016.html
https://random.cesnet.cz/pipermail/nemea/2016-November/000017.html
https://random.cesnet.cz/pipermail/nemea/2016-November/000018.html

A macro `NEMEASUPDIR` must be defined to specify default path for installation of the sup files.

@thorgrin suggested to use `/etc/nemea/sup-available/` as a default value for `NEMEASUPDIR`.

**Comment by janskto1** [comment]
Will not be implemented. This will be fixed with implementation of sysrepo.
